package com.rain.utils;

public enum RainExceptionEnum {

	SUCCESSFULL_SUBSCRIPTION(2000,"SUCCESSFULLY SUBSCRIBED","SUCCESS"),
	SUCCESSFULL_LOGIN(3000,"SUCCESFULL LOGIN","SUCCESS"),
	SUCCESSFULL_APP_REGISTER(4000,"APPLICATION SUCCESFULLY REGISTERED","SUCCESS"),
	SUCCESSFULL_USER_REGISTER(5000,"USER SUCCESFULLY REGISTERED","SUCCESS"),
	SUCCESSFULL_GROUP_CREATED(6000,"GROUP SUCCESFULLY CREATED","SUCCESS"),
	SUCCESSFULL_GROUP_RETRIEVE(7000,"GROUP SUCCESFULLY RETRIEVED","SUCCESS"),
	SUCCESSFULL_GROUP_MAPPED(8000,"GROUP SUCCESFULLY MAPPED","SUCCESS"),
	SUCCESSFULL_USER_FETCHED(9000,"USER INFO SUCCESSFULLY FETCHED","SUCCESS"),
	INVALID_PASSWORD(2001,"INVALID PASSWORD","FAIL"),
	INVALID_REQUEST(2002,"INVALID REQUEST","FAIL"),
	FEATURE_NOT_AVAILABLE(2003,"THIS FEATURE IS NOT AVAILABLE , PLEASE WAIT FOR NEXT RELEASE","FAIL"),
	FIRST_NAME_NOT_FOUND(2004,"FIRST NAME IS EMPTY","FAIL"),
	LAST_NAME_NOT_FOUND(2005,"LAST NAME IS EMPTY","FAIL"),
	EMAIL_NOT_FOUND(2004,"EMAIL IS EMPTY","FAIL"),
	PASSWORD_NOT_FOUND(2010,"PASSWORD NOT FOUND","FAIL"),
	INVALID_SUBSCRIPTION_TYPE(2005,"INVALID SUBSCRIPTION TYPE","FAIL"),
	INSUFFICIENT_USER(2006,"INSUFFICIENT USER LEFT. EITHER SUBSCRIBE FOR BASIC/STANDARD/PRO/UNLIMITED OR TRY DELETING EXISTING USER.","FAIL"),
	APP_NAME_NOT_FOUND(2007,"APPLICATION NAME IS EMPTY","FAIL"),
	OWNER_NAME_NOT_FOUND(2008,"APPLICATION SHOULD BE REGISTER WITH AN OWNER","FAIL"),
	PAYMENT_ID_NOT_FOUND_IN_HEADER(2009,"PAYMENT ID NOT FOUND IN HEADER","FAIL"),
	INVALID_PAYMENT_ID(2011,"INVALID PAYMENT ID ","FAIL"),
	APPLICATION_ALREADY_REGISTERED_WITH_APPID(2012,"ONE MORE APPLICATION IS REGISTERED WITH THIS APP ID","FAIL"),
	ALREADY_SUBSCRIBED(2013,"EMAIL IS ALREADY REGISTERED WITH US AS A SUBSCRIBER. PLEASE VISIT EMAIL TO GET THE SUBSCRIBED TOKEN.","FAIL"),
	EMPTY_DOB(2014,"DATE OF BIRTH IS EMPTY","FAIL"),
	INVALID_DOB_FORMAT(2015,"INVALID DOB FORMAT. PLEASE ENTER DOB IN DD-MM-YYYY FORMAT","FAIL"),
	GENDER_NOT_FOUND(2016,"PLEASE ENTER GENDER FIELD","FAIL"),
	INVALID_GENDER(2017,"INVALID GENDER. PLEASE ENTER MALE/FEMALE.","FAIL"),
	EMPTY_PHONE(2018,"EMPTY PHONE NUMBER","FAIL"),
	USER_ALREADY_REGISTERED(2019,"USER IS ALREADY REGISTERED","FAIL"),
	INVALID_APP_ID(2020,"INVALID APPLICATION ID","FAIL"),
	APP_ID_NOT_FOUND_IN_HEADER(2021,"APPLICATION ID NOT FOUND IN HEADER","FAIL"),
	USER_NOT_EXIST(2022,"USER NOT EXIST ","FAIL"),
	INVALID_CREDENTIAL(2023,"INVALID CREDENTIALS ","FAIL"),
	EMPTY_GROUP_NAME(2024,"GROUP NAME IS EMPTY","FAIL"),
	SSO_NOT_FOUND(2025,"SSO NOT FOUND","FAIL"),
	NOT_AN_ADMIN(2026,"NOT AN ADMIN","FAIL"),
	GROUP_ALREADY_EXISTS(2027,"GROUP WITH SAME NAME ALREADY EXISTS","FAIL"),
	PARENT_GROUP_NOT_EXIST(2028,"PARENT GROUP NOT EXIST","FAIL"),
	GROUP_NOT_FOUND(2029,"GROUP NOT FOUND","FAIL"),
	INVALID_SSO(2030,"INVALID SSO","FAIL"),
	EMPTY_GROUP_ID(2031,"GROUP ID IS EMPTY","FAIL"),
	USER_ALREADY_MAPPED_TO_GROUP(2032,"USER ALREADY MAPPED TO THIS GROUP","FAIL"),
	
	;
	
	
	private int code;
	private String message;
	private String status;
	
	
	public String getStatus() {
		return status;
	}


	public int getCode() {
		return code;
	}


	public String getMessage() {
		return message;
	}


	private RainExceptionEnum(int code, String message,String status) {
		this.code = code;
		this.message = message;
		this.status=status;
	}
	
	
}
